apiVersion: v1
kind: Secret
metadata:
  name: billing-service-secrets
type: Opaque
stringData:
  DB_HOST: "mysql-billing"
  DB_PORT: "3306"
  DB_USER: "billing_user"
  DB_PASS: "billing_pass"
  DB_NAME: "billing_db"
  JWT_SECRET: "change-me-in-production"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_REGION: "us-east-1"
  SQS_BILLING_QUEUE_URL: ""
  SQS_OS_QUEUE_URL: ""
  SQS_EXECUTION_QUEUE_URL: ""
  MERCADOPAGO_ACCESS_TOKEN: ""
