apiVersion: v1
kind: Secret
metadata:
  name: billing-service-secrets
type: Opaque
stringData:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  DB_NAME: ${{ secrets.DB_NAME }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  SQS_BILLING_EVENTS_QUEUE_URL: ${{ secrets.SQS_BILLING_EVENTS_QUEUE_URL }}
  SQS_OS_EVENTS_QUEUE_URL: ${{ secrets.SQS_OS_EVENTS_QUEUE_URL }}
  SQS_EXECUTION_EVENTS_QUEUE_URL: ${{ secrets.SQS_EXECUTION_EVENTS_QUEUE_URL }}
  MERCADOPAGO_ACCESS_TOKEN: ${{ secrets.MERCADOPAGO_ACCESS_TOKEN }}
